import express from 'express';
import http from 'http';
import { Server as IOServer } from 'socket.io';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();
import bossesRouter from './routes/bosses.js';
import mapsRouter from './routes/maps.js';
import questsRouter from './routes/quests.js';
import goonsRouter from './routes/goons.js';
import webhooksRouter from './routes/webhooks.js';
const app = express();
app.use(cors({ origin: process.env.FRONTEND_URL || true }));
app.use(express.json({ limit: '5mb' }));
app.use('/api/bosses', bossesRouter);
app.use('/api/maps', mapsRouter);
app.use('/api/quests', questsRouter);
app.use('/api/goons', goonsRouter);
app.use('/api/webhooks', webhooksRouter);
app.get('/health', (req,res)=>res.json({ok:true}));
const server = http.createServer(app);
const io = new IOServer(server, { cors: { origin: process.env.FRONTEND_URL || '*' } });
const PORT = process.env.PORT || 5000;
server.listen(PORT, ()=> console.log(`Backend listening on ${PORT}`));
